task: detection
num_classes: 1
remap_mscoco_category: false
train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/InfraredSmallTargetDetection/datasets/prepared/rtdetr_gpt_low_contrast_combined_v1/images/train
    ann_file: D:/InfraredSmallTargetDetection/datasets/prepared/rtdetr_gpt_low_contrast_combined_v1/annotations/instances_train.json
    transforms:
      type: Compose
      ops: null
  shuffle: true
  batch_size: 1
  num_workers: 0
  drop_last: true
val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/InfraredSmallTargetDetection/datasets/prepared/rtdetr_gpt_low_contrast_combined_v1/images/val
    ann_file: D:/InfraredSmallTargetDetection/datasets/prepared/rtdetr_gpt_low_contrast_combined_v1/annotations/instances_val.json
    transforms:
      type: Compose
      ops: null
  shuffle: false
  batch_size: 1
  num_workers: 0
  drop_last: false
