__include__: [
  './deim_r18vd_120e_coco.yml',
]

num_classes: 6
remap_mscoco_category: False
eval_spatial_size: ~

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/BaiduNetdiskDownload/wdd_work/data/car_union_sliced_smoke/train
    ann_file: D:/BaiduNetdiskDownload/wdd_work/deim/data_car_union/car_union_smoke_train.json
    return_masks: False
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction
    base_size: 640
    base_size_repeat: 1

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/BaiduNetdiskDownload/wdd_work/data/car_union_sliced_smoke/val
    ann_file: D:/BaiduNetdiskDownload/wdd_work/deim/data_car_union/car_union_smoke_val.json
    return_masks: False
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
    base_size: 640

output_dir: ./output/deim_car_union_smoke

epoches: 2
