__include__: [
  './deim_r18vd_120e_coco.yml',
]

num_classes: 6
remap_mscoco_category: False
eval_spatial_size: ~

# 微调: 小 lr(0.00005), 12 epoch
optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.
  lr: 0.00005
  betas: [0.9, 0.999]
  weight_decay: 0.0001

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/BaiduNetdiskDownload/wdd_work/data/car_union_ft1k_1280/train
    ann_file: D:/BaiduNetdiskDownload/wdd_work/deim/data_ft1k/ft1k_train.json
    return_masks: False
    transforms:
      policy:
        epoch: [2, 8, 11]
      ops:
        - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5],
           probability: 1.0, fill_value: 0, use_cache: False, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [960, 960], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
  shuffle: True
  num_workers: 4
  drop_last: True
  total_batch_size: 8
  collate_fn:
    type: BatchImageCollateFunction
    base_size: 960
    base_size_repeat: 1
    stop_epoch: 12

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/BaiduNetdiskDownload/wdd_work/data/car_union_ft1k_1280/val
    ann_file: D:/BaiduNetdiskDownload/wdd_work/deim/data_ft1k/ft1k_val.json
    return_masks: False
  shuffle: False
  num_workers: 4
  drop_last: False
  total_batch_size: 16
  collate_fn:
    type: BatchImageCollateFunction
    base_size: 960

output_dir: ./output/deim_ft1k

epoches: 12
flat_epoch: 6
no_aug_epoch: 1
